ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "packSize" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "ingredients" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "material" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "highlights" TEXT;
